{% set name = "pyimgur" %}
{% set version = "0.7.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  # url: https://github.com/Damgaard/{{ name }}/archive/{{ version }}.tar.gz
  sha256: ebe78b65d4aed5d0cd339abe6baed4ce4aebc46bce1464976cf4733b84e39eed

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - requests

test:
  # Currently test files are not included in source dist so only check import
  requires:
    - python {{ python_min }}
  imports:
    - pyimgur

about:
  home: http://github.com/Damgaard/PyImgur
  license: GPL-3.0
  license_family: GPL
  license_file: COPYING
  summary: 'The simple way of using Imgur.'
  description: |
    The simple way of using Imgur.

    You can upload images, download images, read comments, update your albums,
    message people and more. In fact, you can do almost everything via PyImgur
    that you can via the webend.
  doc_url: https://pyimgur.readthedocs.org/
  dev_url: https://github.com/Damgaard/PyImgur

extra:
  recipe-maintainers:
    - megies
