travis:
  secure:
    BINSTAR_TOKEN: O2DB9hTykt5kS2Yw3C8R4vZeGkws9RJ5BiWvMk38sbSy+RHFVebCuI9KeDnQLWr+x99K9Hwg8f7zG+9QFP9mBb0BxmdnjqTn9bvAs0Mg63hU85gK1lN5GTanPERz09LUlXNTFBJDQT1ufmWAhDG5Qkw5ZYF0KZAlAgG+mSF2GEvRfId28YLjMIWJfy0WU7O79O7joYJhN54Yb4tPZmIqudzbo/1qz+MsXocqLuWlY4mfc7aGNhpzG6zjET5JAGebqXAOWM1OQlppsVivjz+rqZZjiT8liFLxtHN41bstRg5tBn0rogKu0Zmawi5kDjXjRTEhvHQe4lRuz7xTpyDypoQSl9qMUHgFCJZy7l4Qmq4sbIlF3z6tncTRi9ji8Xb2JzenDnAoQXoldVOd0NQM1xX0jRQI2cE9Q10+xD+v98OHmBv3+4Omq+CqZqBiCJeIqsEkXrH+lgRq51lW8WopqCsn9S8LixWSl/NDu+H6WUV1G0TqqdD7OII5o4FNstmFvl3Bk1gANc9hY71gUMfiD+GAQH6lG/VaXGeUhJ1KjRxH+Ccl6w3DgzWZFVb2IKMnhkuEh3JTG+lb2XwWonpDxQRQH4yTXp+Wu3hwMXmV32DOTKP7lt0IDyf/8l1CGxv6hSO0yByIhyG+vYFPoup9MpMzMtgZ2iu7z+BquBspZik=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
